### ISSUE TITLE
enhancement search for empty bookmark folders

### ISSUE THREAD

**Issue by Bamajon1974** [cadeyrn/bookmarks-organizer#132]
Is Bookmarks Organizer still being developed and maintained? 

Anyway, I do have a feature request. Can a search for empty bookmark folders feature be implemented?

Thanks in advance!

**Comment by cadeyrn** [comment]
> Is Bookmarks Organizer still being developed and maintained?

Yes. It's not a priority at the moment but the feature development will be continued in a few months.

**Comment by Bamajon1974** [comment]
Great! Thank you! Just wanted to make sure the extension wasn't abandoned.

-Jon

**Comment by Thomas-D-C** [comment]
For info, [Bookmark Dupes](https://addons.mozilla.org/fr/firefox/addon/bookmark-dupes/) is able to do that.
Except that empty folders have to be really empty, not containing any separator, because Bookmark Dupes does not handle separators, and consider folders containing only separators as not empty.

I hope that Bookmarks Organizer will work around that. :-)
(I have too may folders containing only separators to handle them by hand.)

**Comment by Thomas-D-C** [comment]
Same as #12 .
