### ISSUE TITLE
bookmarks organizer is not a mozilla recommended add-on

### ISSUE THREAD

**Issue by jonhp** [cadeyrn/bookmarks-organizer#133]
bookmarks organizer is not a mozilla recommended add-on. how do we know that it is safe?

**Comment by cadeyrn** [comment]
Only a very, very small portion of all add-ons are part of Mozilla's recommended extensions program. It doesn't mean at all that other add-ons are not secure. Security is only one criterion to be part of the recommended extensions program. All add-ons on addons.mozilla.org received a review and were checked for security issues. I also got recommendations by Mozilla's reviewers in the meet their high standards. I am not a unknown add-on developer, one of my other Firefox add-ons has more than 100,000 users and is part of Mozilla's recommended extensions program. All my add-ons are open source. This means everyone can check the source code. And there is international press coverage for my add-ons, for example three (!) articles about Bookmarks Organizer on ghacks:

https://www.ghacks.net/2017/05/20/bookmarks-organizer-for-firefox/
https://www.ghacks.net/2018/03/14/bookmarks-organizer-2-0-for-firefox-released/
https://www.ghacks.net/2019/01/01/bookmarks-organizer-3-0-for-firefox-includes-whitelist-functionality/

This is a strong indication that Bookmarks Organizer is safe.

I will close this issue because it doesn't contain anything I can work on. But thanks for asking and feel free to ask more questions.
