### ISSUE TITLE
Firefox keyword search bookmarks can be broken

### ISSUE THREAD

**Issue by 894-572** [cadeyrn/bookmarks-organizer#134]
[The Firefox keyword search](https://support.mozilla.org/en-US/kb/Smart%20keywords) breaks for at least Wikipedia bookmarks.

For Wikipedia (en) the keyword

`https://en.wikipedia.org/w/index.php?title=Special%3ASearch&search=%s`

is converted to

`https://en.wikipedia.org/wiki/%25s`

The search doesn't work anymore.

**Comment by cadeyrn** [comment]
I think (because you didn't mention it) that you're referring to the feature to correct redirects. There is nothing I can do. If you enter this URL into the address bar you will see that there is a redirect. The add-on can't know that the "%s" is a placeholder for a keyword search. But you can add the bookmark to the whitelist, then Bookmarks Organizer won't complain again.

**Comment by 894-572** [comment]
> 
> 
> I think (because you didn't mention it) that you're referring to the feature to correct redirects. 

Yes, correct.
