### ISSUE TITLE
English correction

### ISSUE THREAD

**Issue by tinabea17** [cadeyrn/bookmarks-organizer#144]
When you say, Firefox will “loose” the tags associated with the bookmark, you mean LOSE the tags, as in, they will be deleted.  ( very silly image inny head, hundreds of free-range tags, roaming about with no home)
![Screenshot 2020-07-18 16 47 03](https://user-images.githubusercontent.com/20605195/87862498-735a9080-c916-11ea-9a4f-cac948131d51.png)

**Comment by coffeemesh** [comment]
I think the way it is described right now makes sense. Especially if you refer to the [discussion](https://bugzilla.mozilla.org/show_bug.cgi?id=1440988#c2) exactly about this behavior. Firefox **will** "loose" them and not loose them literally although I am understanding that they will appear gone since the original URL is no longer there.

**Comment by cadeyrn** [comment]
Thanks, it's fixed.
