### ISSUE TITLE
Problems with Facebook Bookmarks - Declared as "dead" - Allow whitelisting of domains

### ISSUE THREAD

**Issue by pstein** [cadeyrn/bookmarks-organizer#213]
As I found out BO declares a lot (all ?) bookmarks from facebook.com as dead (red dot) although they are accessible.
Example:

https://www.facebook.com/qbar.aschaffenburg1/?locale=de_DE

I am currently not logged in in Facebook. And I don't want to login just to run BO.
BO should recognize these facebook URLs as alive.

I think this is a bug.

At least I would like to have an option to whitelist whole domains.
Otherwise my result list is stuffed with invalid facebook alerts

Can this be added in the next release?

Thank you

**Comment by cadeyrn** [comment]
Starting with Bookmarks Organizer 4.1 bookmarks for facebook.com will no longer be checked because Facebook prevents it. A solution would be to override the Access-Control-Allow-Origin response header but this is currently not allowed for Manifest v3 extensions. Should this be allowed in the future something like that will be implemented.

**Comment by cadeyrn** [comment]
@pstein Bookmarks Organizer 4.1.0 has been released and it includes the mentioned change.

**Comment by Illegal-Services** [comment]
@cadeyrn Firefox have fixed this issue: https://www.mozilla.org/en-US/firefox/117.0.1/releasenotes/
I have tested it and the console error message about the background doesn't happen anymore.
All good, you can as planned remove the hack in BO [v4.1.1]https://github.com/cadeyrn/bookmarks-organizer/releases/tag/v4.1.1
