### ISSUE TITLE
Has Problems with other Extensions

### ISSUE THREAD

**Issue by ScottNAtlanta** [cadeyrn/bookmarks-organizer#31]
I could not get this to work so I created a clean profile where bookmarks-organizer was only extension installed and it worked.  I have the following extensions installed
Adblock Plus
Adblock Plus Pop-up Addon
Disconnect
Greasemonkey
LastPass
NoScript
Bookmarks Organizer

I did notice that the window in which this add on executes also has the NoScript red circle around it but does not give the option to unblock any script that could be running

**Comment by cadeyrn** [comment]
I don't know how NoScript works (I never used such an add-on) but I know that script blockers can block the add-on's scripts. I know that from uMatrix users that the add-on didn't work until the add-on was allowed to execute the script. Unfortunately I can't do a lot about this issue because I can't bypass script blockers. The only what I can do is to add some documentation to the README file / add-on description.

**Comment by cadeyrn** [comment]
Added a bit of documentation to the README and on addons.mozilla.org.
