### ISSUE TITLE
All tags are removed when reparing or editing a bookmark

### ISSUE THREAD

**Issue by Mellthas** [cadeyrn/bookmarks-organizer#47]
All tags are removed from a bookmark, if I choose to repair a redirect automatically or manually edit the bookmark through the Bookmarks Organizer interface.

Tested with Firefox 54.

**Comment by cadeyrn** [comment]
That's a Firefox bug. I created https://bugzilla.mozilla.org/show_bug.cgi?id=1440988. Thanks for reporting.

**Comment by cadeyrn** [comment]
It's not a bug, it's the behaviour of Firefox. Tags are bound to the URL and not to the bookmark so if you change the URL of a bookmark, the tags are not lost, the tags are still there for the old url. Please see the discussion in the bugzilla ticket above.

I agree it's very confusing. Maybe things will change in the future. But for now I have to close the ticket because it's neither a bug in Bookmarks Organizer nor in Firefox.

Anyway, thanks for reporting, it was new for me, too. And who knows, maybe the bevaviour will be checked.

**Comment by Mellthas** [comment]
Thanks for the clarification!

**Comment by cadeyrn** [comment]
You're welcome.

I added a note to the README:
https://github.com/cadeyrn/bookmarks-organizer/blob/master/README.md#notes--known-issues

I will also add this note to the description on addon.mozilla.org once Bookmarks Organizer 2.0 is released.
