### ISSUE TITLE
Option to ignore http -> https redirects from warnings in error check

### ISSUE THREAD

**Issue by JustMyGithub** [cadeyrn/bookmarks-organizer#50]
I was suprised how many of my bookmarks have a "warning" when I check whether they are still available. I noticed most of the redirect to the very same page just appending the s to http.
In order to see relevant warnings, I would like to be able to filter those redirects.
It would also be nice if one could click "warning" or "error" and then omit findings from the other category.

Thanks

**Comment by syldub69** [comment]
I have the same problem... Actually I use an extension which automatically replace http by https (Smart HTTPS), so Bookmarks Organizer detects all my http bookmarks in Warning. My workaround is to disable Smart HTTPS during the "broken bookmarks" scan... but it would be good if an option exists to ignore http/https protocol, and just focus on the URL.
See my screenshot here :
![2018-01-14_21-36-35](https://user-images.githubusercontent.com/16567425/34921081-a0a7ddc4-f97d-11e7-9b98-523175f0e865.jpg)

**Comment by cadeyrn** [comment]
I don't understand why it's necessary to disable another add-on. Why not changing the outdated URLs?

**Comment by syldub69** [comment]
I don't want to change the outdated URLs because I want to keep the standard http version of the web page in my bookmarks. I don't use the HTTPS redirector on all my Firefox profiles.

**Comment by cadeyrn** [comment]
> I want to keep the standard http version of the web page in my bookmarks.

For which reason?

**Comment by syldub69** [comment]
HTTP version is often always reachable. HTTPS sometimes is disable. Using HTTP, I am sure I can at least reach the website. Then my additional addon tries if a HTTPS version exists.

**Comment by cadeyrn** [comment]
I don't see the relation to my add-on. Bookmarks Organizer only suggest redirects to a HTTPS version if the website redirects to a HTTPS version. This means there is no way to reach the HTTP version of the bookmark. Therefore there is no reason not to correct the bookmarks. The only consequence is that you save a redirect per bookmark.

**Comment by syldub69** [comment]
Bookmarks Organizer doesn't suggest redirects to a HTTPS version by itself.
Some website are redirecting by themselves because webmasters have updated the website structure, or migrated the pages/domain). In this case your addon is great.
But I'm not talking about this "natural" redirection.
When accessed to their HTTP version, some websites doesn't redirects to their existing HTTPS version. That's why I use my another addon, which always looks if an HTTPS version exists and then redirects to it.
On some Firefox profiles, I don't use this redirection addon, on some another I do.
Your addon is "strict" : it sees & analyze the final URL, after websites redirection AND eventual browser/addon redirection.

**Comment by cadeyrn** [comment]
There is no way to distinguish.

And honestly I still don't see an use case why these URLs shouldn't be changed. If the user installs another add-on then I have to assume that the user wants the result of the add-on because it was a explicit decision to use the add-on. The goal of this feature of Bookmarks Organizer is to avoid unnecessary redirects.

**Comment by syldub69** [comment]
As I said before, I don't use my HTTPS redirection addon on all my Firefox profiles (but all my bookmarks are synchronized on all my profiles).
Your proposition is to create a new HTTPS bookmark for each HTTP bookmark for which a HTTPS is working (because I need to keep the HTTP bookmark). That is not conceivable.
It seems you don't understand the need. So that's why I said at the beginning : 
_My workaround is to disable Smart HTTPS during the "broken bookmarks" scan..._ 
Being able to disable the protocol verification would have been an interesting feature though... as asked by the topic creator.

**Comment by cadeyrn** [comment]
Closing this ticket as WONTFIX. Bookmarks Organizer show all redirects as warning. You can fix the URLs or you kann keep the redirects. But it doesn't make much sense to repair redirects with more changes than http->https and to not repair the redirects with only http->https, either you're interested in fixing these or not. There is no reason to distinguish.

Also

> It would also be nice if one could click "warning" or "error" and then omit findings from the other category.

is implemented since the first version of Bookmarks Organizer.
