### ISSUE TITLE
bookmarks tags support  (Firefox Places)

### ISSUE THREAD

**Issue by TarekJor** [cadeyrn/bookmarks-organizer#52]
Please **add tags support** for this **WebExtension** on **Firefox** (**tags is a exclusive** **Firefox Places** feature but it is supported by **Pinboard** or **Delicious** and clones **SemanticScuttle** or **Shaarli**)

*this solves this issue too (#47)

**Comment by cadeyrn** [comment]
Please specify what exactly should be supported by Bookmarks Organizier. I don't know what you expect when you say "tags support for this WebExtension".

**Comment by cadeyrn** [comment]
There is no tags support for WebExtensions on the platform side. So there is nothing I can implement.

**Comment by dzmitry-lahoda** [comment]
@cadeyrn , WebExtensions  do  not have access to tags?

**Comment by TarekJor** [comment]
@cadeyrn, I thought WebExtensions 'standard' had some kind of evolution in bookmarks API with 'tags support' for bookmarks (JSON, XML, etc), if not on February, at least now or eventually, in near future... if not, it is a bad design, as I think bookmarks as crucial and useful tool...

'feature' closed for now, (a 'too generic' issue or generic feature request, it was not my objective, sorry.)

**Comment by cadeyrn** [comment]
I don't know what the relation is between tags and the formats JSON and XML, but no, there is support for tags in Firefox. An request to implement this sometime in the future has been approved but  this won't happen until Mozilla has rewritten their backend APIs. There is a lot of work ongoing to improve the general architecture of the places system.

**Comment by dzmitry-lahoda** [comment]
https://github.com/WorldBrain/Memex/issues/508#issuecomment-416100204

https://bugzilla.mozilla.org/show_bug.cgi?id=1225916

**Comment by cadeyrn** [comment]
Yes, that's the bug I was referring to (approved request, but on hold until the platform work has been done).

Regarding the Memex issue: to develop external applications for macOS, Windows and Linux is not an option for me. Also the use of an WebExtension experiment is not an option because this only works for pre-release versions of Firefox. The only viable option is the use of an WebExtension API. But we have to wait until the API has been implemented.
