### ISSUE TITLE
Firefox 60: bookmarks with addons.mozilla.org as URL are reported as broken

### ISSUE THREAD

**Issue by cadeyrn** [cadeyrn/bookmarks-organizer#76]
Firefox 61: bookmarks with addons.mozilla.org as URL are reported as broken. Does not happen with Firefox 59.

**Comment by cadeyrn** [comment]
14:36.19 INFO: Last good revision: f96e8d3c02251534d208bafb046d007970e284a5
14:36.19 INFO: First bad revision: 270f423f416617ed31f2ee448c73af100941a6d3
14:36.19 INFO: Pushlog:
https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?fromchange=f96e8d3c02251534d208bafb046d007970e284a5&tochange=270f423f416617ed31f2ee448c73af100941a6d3

**Comment by Gitoffthelawn** [comment]
I actually experience this with FF60b4.  And it's not just addons.mozilla.org, it's `*.mozilla.org` and `*.firefox.com`.

Setting `user_pref("privacy.resistFingerprinting.block_mozAddonManager", true);` should fix this, but it doesn't anymore.  I wonder if Mozilla changed the pref name... I seem to remember reading that they were going to do that.

**Comment by mpopp75** [comment]
I get many more bookmarks listed as broken which aren't. Some of these are:

https://dev.opera.com/
https://developers.google.com/
https://sc.omniture.com/login/
http://gs.statcounter.com/
https://mail.google.com/
https://www.linkedin.com/
https://twitter.com/
https://www.amazon.de/
https://www.ebay.com/
https://www.apress.com/de/
https://banking.ing-diba.at/

... so mostly very well-known web sites.

**Comment by Gitoffthelawn** [comment]
Perhaps there could be an advanced mode to allow users to still check URLs in `addons.mozilla.org`.

Since it has been added to Bookmark Organizer's internal skip list, there's now no way to check those URLs.

But, at least as of FF60, FF could still handle this by simply adding `addons.mozilla.org` to `extensions.webextensions.restrictedDomains` and setting `user_pref("privacy.resistFingerprinting.block_mozAddonManager", true);`

I haven't tested this technique recently, so it would need to be verified that it still works.

**Comment by cadeyrn** [comment]
addons.mozilla.org has to be removed (not added) from extensions.webextensions.restrictedDomains. But doing this enables a security vulnerability [1], so I won't support anything that causes users to change this setting.

[1] https://www.mozilla.org/en-US/security/advisories/mfsa2018-11/#CVE-2018-5152
