### ISSUE TITLE
Tracking protection interference

### ISSUE THREAD

**Issue by happysurf** [cadeyrn/bookmarks-organizer#77]
In Firefox 60beta with Bookmarks Organizer 2.0 loaded if you go in > Option> Privacy and Security > Tracking Protection > the options are gray out with this warning >  **An extension,  Bookmarks Organizer, is controlling tracking protection.**
It's very strange.

**Comment by cadeyrn** [comment]
> the tracking protection of Firefox no longer causes that some working bookmarks will be reported as broken! That's why Bookmarks Organizer needs the permission to read and modify the privacy settings and to control the tracking protection setting of Firefox beginning with version 2.0.0. Note: Only one extension can control the tracking protection setting at a time. If another add-on controls this setting, Bookmarks Organizer cannot use this enhancement.

https://github.com/cadeyrn/bookmarks-organizer/blob/master/CHANGELOG.md#enhancements

I will convert this strict permission to an optional permission so that users can opt-in this behaviour.

**Comment by happysurf** [comment]
Thanks for the info, in any case I don't use tracking protection in favor of ublock Origin.

**Comment by cadeyrn** [comment]
To clarify the situation: The tracking protection was diabled during the check for broken bookmarks in Bookmarks Organizer 2.0. This change was reverted in Bookmarks Organizer 2.0.1 which was released on the same day due to review feedback. With the next update, Bookmarks Organizer 3.0, this feature will still be disabled. So at the moment there is nothing actionable in this ticket. But the long term plan is still to re-introduce this feature with an opt-in. So leaving this ticket open for this work.

**Comment by cadeyrn** [comment]
I don't plan to do re-introduce a tracking protection setting for the reason I mentioned a few years ago. Instead I will add a notice that the tracking protection setting can influence the results. That's a duplicate of #109.
