### ISSUE TITLE
Google links show as warnings, Mozilla add-ons are errors

### ISSUE THREAD

**Issue by ChooChooAl** [cadeyrn/bookmarks-organizer#88]
https://mail.google.com/mail/u/0/?tab=wm#inbox
All of my firefox add-ons and thunderbird add-ons show error.
ie. https://addons.mozilla.org/en-US/thunderbird/complete-themes/
facebook

also a lot of my google links show as warnings.
google photos, google shopping list, google contacts, google drive, google calendar.  These seem to want to go to account sign in when it's not needed at least from my viewpoint in my browser.

Delta airlines shows error  https://www.delta.com/ wants to redirect but the link works and does not redirect.

**Comment by cadeyrn** [comment]
It's no longer possible to check some Mozilla websites since a security change in Firefox 60 to protect some Mozilla services. There is nothing I can do. I will release an update soon to exclude these Mozilla domains. That's #76, so marking as duplicate.

Warnings are redirects. There is also nothing I can do. If the server says there is a redirect Bookmarks Organizer shows that there is a redirect.
