### ISSUE TITLE
Detecting duplicates with anchors and no canonical link relation

### ISSUE THREAD

**Issue by gizmecano** [cadeyrn/bookmarks-organizer#94]
I don't know on what basis the duplicates detection is based, but it seems that this operation doesn't integrate anchors added by different sites (including those used for tracking).

For example, by searching for the page dedicated to your own extension (on the Mozilla Add-ons site) using several criteria and adding results into bookmarks, none of these entries are detected to be duplicates:

1.  [assumed default English page](https://addons.mozilla.org/en-US/firefox/addon/bookmarks-organizer/)
2.  [page found using the search form](https://addons.mozilla.org/en-US/firefox/addon/bookmarks-organizer/?src=search)
3.  [page found from a collection page](https://addons.mozilla.org/en-US/firefox/addon/bookmarks-organizer/?src=collection)

I noticed that this page seems not to use any [canonical link relation](https://tools.ietf.org/html/rfc6596). So, logically, if the duplicates detection mechanism is based on a possible existence of this canonical link, no screening can be correctly performed. However, finding a way to include in the duplicates detection this type of anchors added to the canonical URL would be an undeniable improvement.

**Comment by cadeyrn** [comment]
Hi,

thank you for your report.

Bookmarks with different parameters in the URL are different bookmarks and no duplicates. It's not possible to say that different URLs represent the same website because one different URL parameter could be enough to serve totally different content. If you add a bookmark for one of these links in Firefox you will see that the star is not blue for the other URLs.

For this reason the check for duplicates in the Bookmarks Organizer only checks the URL of the bookmark.
